/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_calculate_chop_penalty: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number) => void;
export const wasm_calculate_cong_penalty: (a: bigint, b: number) => bigint;
export const wasm_calculate_count_cards_settlement: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number, h: number, i: number) => void;
export const wasm_calculate_elo_delta: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const wasm_calculate_rotten_penalty: (a: number, b: number, c: number, d: bigint, e: number) => void;
export const wasm_calculate_traditional_settlement: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number, h: number, i: number) => void;
export const wasm_calculate_winner_takes_all_settlement: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number, h: number, i: number) => void;
export const wasm_can_beat: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasm_can_chop: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const wasm_check_instant_win: (a: number, b: number, c: number, d: number) => void;
export const wasm_compute_table_elo_settlement: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => void;
export const wasm_create_deck: (a: number) => void;
export const wasm_deal_cards: (a: number, b: number, c: number, d: number) => void;
export const wasm_decide_bot_move: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const wasm_evaluate_candidate_moves_mcts: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => void;
export const wasm_get_available_smart_variants: (a: number, b: number, c: number) => void;
export const wasm_get_optimal_move_hint: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const wasm_get_sorted_quick_select_candidates: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const wasm_identify_combination: (a: number, b: number, c: number) => void;
export const wasm_partition_hand: (a: number, b: number, c: number, d: number) => void;
export const wasm_pass_turn: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasm_play_move: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const wasm_simulate_match_series: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const wasm_simulate_single_table: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const wasm_simulate_tables_batch: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const wasm_sort_smart_groups: (a: number, b: number, c: number, d: number) => void;
export const wasm_start_new_game: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const wasm_validate_move: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const __wbindgen_export: (a: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export2: (a: number, b: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
